; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
; No external LoRa libraries - using custom driver in lib/SX1262_Custom
upload_protocol = serial
upload_port = COM5
upload_speed = 115200
monitor_speed = 115200
monitor_port = COM5
; Output Intel HEX format for flashing with MCU ISP tools
board_build.mcu = stm32f103c8t6
board_upload.maximum_size = 65536
build_flags = 
	-D HAL_UART_MODULE_ENABLED
	-D ENABLE_HWSERIAL1
upload_flags =
    -i
    dtr,-rts,rts:-dtr,-rts,rts